project:
  type: website
  output-dir: docs

website:
  title: "Julian Langenhagen"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      
  google-analytics: "G-CL2F0K5V90"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

