project:
  type: website
  output-dir: docs

website:
  title: "jlangenhagen.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  google-analytics: "G-CL2F0K5V90"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

